### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by Rivaldiananto** [HomelessPhD/AR_Puzzles#10]
Hi, thanks for making this code.. but i think something wrong in it, cuz when i run it with a right password on puzzle 1. Your code cant match it. 

note: i changed the msg first and add another Caps on it.

you can try it,

msg = "U2FsdGVkX198sEaJRcXaYj74/Wt1qw2tcmf5aSfr5YCNnuKz7ys3+VP/QSeF+8z4ngk36IS4pkVRSzjxq7GgrIEm/1Igh7/lluddtYpzxsUbOrQHxpmPv9cQzkcod8IjAQo4BIRSiLVDQE9wECUuG0DItRkum0gb1puM0EgAqnFv/dkE7RkqPlhyErCgHtZt/fuyGv/xCODiZs14/W/rS2wj4cgM0afUdv/xAkMox7iiSvF5u+5uZcwSkl6kSATovWgHsdoK8yJVNlkqAb5RAt2WhYGxVEOc80Ju/iAB2caq72S8FybBVlwohTjTHhYcnmye3GjpAJZ9t9gsAh0C4PhEpebGOSMp34wchsK7Oxj2Jkxw4NCvKt4INsFMp2xFyoHvVf4ro3WjRKkpLbU9ci4yOsPN1LmaWd6PY9sSn9E3ixWlW8FkQQ6fp6LWYuCFqrdqzv+cumKeIuHf88+POfed6L1xeDCnmjuqsJ3x5YkNuJrMh2O3f4ZRQEBY9rAnxt/Y2/F0T6VXMODMN1Y+kxwbDB0wORBXvUUvrkwr9ACo/t5N3nDpQhYBKL4ZVjTpSqhLLd8IkBFw3LWZXr+TW8xGWWkm0I9xVVlMegNV2bN2BS3eM9LgJj3C0/WbBiamp2ZkHrWuoTOpfZZoyKaCQsrPxW5pyhMxY+9Lap6HXUANxo5VMUxlX+jjo0kop/Hbmw+Mj9FxuZ8NRHR1mc9aML/Lt6UM0/5u2RrqaZlQIdXtQXCuLfb4s4dG6eTp0R2dtRiLsqJg9+NzUjZF/zzrzwBXFL+jSpK5fu8bq6/BQYzx++GJxGH+u3YpXlxubnZRfZML4E4vjjxHzkgMo/gdP1+jHlAcsWsDHHWPLDfz0TvZZWjMjt5xO8mkmZkLVF742kLonhDAZhwI/UpZU9hVq6R/zri8XglA+uxsmQaM1EKaZ6KfJam/YBRiDhoMiooAVyt/Bu20EzP0uQrbfaUcQOQrNCEkIokKp5V7kYFFyyWmtZjiKPSMqNbMBbUVSnuCkevjVJkVOPbalHPBRc1InP60oyFVYvuEDcpExHpCGrXFZOaVJ7IXM3j1t3ykx+ePd1rllJ0dqOe6xMkvXHZSdk46WgvtPsG7cY1CnPeInmwyLVdBiI6SjVTtTd/a66hT9h2VwHaqa6DJeZ/jzaFctILYqSDXP5RKYxKbbn25Bhfk3ZR/SbgJFgveRmir5HpNqcx2LYNhjmuk1DlbVNNmED7IYssXUY1zhLZ0r1Ly54JVnzQIHZu4uMO8e35IfaBaHDf7xK08AqS20Ek3P6nP943C85Yl37jyXODvD9mTwI1HjFWoRvV0OzVTCfspn1aJEbH7POxTsnssHVSGO9bucBSzoKA/tkQnefnOEBS0FtRxr2tvvbVtXlKXnwVV9F/4KJhZ2BjkASN8YxFYHi2oMR4r3qEGV+HHO4oGu/ioJfpLNDMiS2WJ4POhRuG1SDItepg5/6meMUULpMlVRx/ZcSCqB2TjhxO8EI8NucyfVQ36M0JRBb4n8s7QAUzfIOcJPpqeIl82o30BR7D+9b5gF4aFR+2p/LnwZEeuDxhgl6V2h30Hoy7t1NtbH5eepGx+1CQAIg31PJxJZUeT84mf458Hjgr2b5b1JLMskcPThyRGNqXE4odsMzqTtA5VlagVmMvmtGlK/1FAzHQzoTIvlSe/MpeOkP9pnr1JAy6n2Cvxy/468DelndAba2FqEEfY7Q/aHcBHWd258g8USBhabUFZ9zhsddyTcTvQHynt0VnhWa0Ea6DJhG8OJL5HmbQmbbcB0+hGA8BitkXHqjJE4U3CP+lfMAu7Z1OJaPNDPe4lK8SmjfHUrSeT7a1JXwbrclTnUFhz1RrdnCH61AJOhq6xLQYfYDudzAaVLmB7bEChjaAi3A5K7I8Jk/mqRrEm/e9Y1/pBLZ3sQ6kVwZYrh0GxrHV/+5Z72bQTzDtqaBYNCRuVpSsszLYdGr6Seez3uShrOrMwOF95BxVh6hyNg2ztwFvXkazDJidvzoPOTKgdgvDVVmyJkoH4KJwIxfnqee+Ma+qU1SHBc+qGT0ATOKULjeLw/3lhyufC0oKoyGQ5m5SCTPKas/opD4RMIlSLbRjVh2+xqK1zbEPVR5893HP5SrUSGDWSDgFW3kxPatm+e8C16wpgu/mcqAd7D5EbPuNhLXlBJpD5yRb+az+eyBeNwJEsS+l68Qm03qd/WJFYdZOUfJmq/XtbppBQcihWBzZQkS/mzJHjCAWZHuu0PhLcYyJg4DwEMKMqzDQAqR72XBo8F5kO4Q1ctIioVn7C4Evtnhl0qpT47T5f4jkSqbcVYVrLGwUQz1aWVP3NCFNqrs2gTlJrZ4lvyhoxm39MEJPgyq5aEO0yZReC1vuZZxXVteHmQT+GX8fE8wc7Hsqo0/7DqZtn8GLVO+UVrHMFFmiYc7gE3fc/zWKp6oceFSlAVFFh7j+NmIucze0Lh0g9NJTTwQf/rg2flDpgMZPbl0rUVzkhC5paI9FNHtjESmTh0FaadFfL89qW0ZBFnnW1IUCIqEKRTR4OKmh/TPvi1Vyd6gvoHDohM8exGpmvykhGL0+n7LPtPctrrmVI/nDZS+UFrsTKEwz5mJcyraceWMzdTu/wxMWDckRxwVBx3dbQknfJXgi/WjnT8tjksOyR2Ux8EGjYW7u3hyHcNVDJ2P6Qx9TyWbR15ImSZcSq5A7NCubOw7hXCKHq9Z7YskYwOUV6rvpPZi/C737LJErFuz8vvJ7KaQ5aCFZvIMcCPVlos+XMDOdM7eQmQw23fHCdAhRLCPZxEd3QWE8lvEI+tmm+z3SS8dpDK8QEkBijQ/lrdRKaNq94qDUIcKIsci7Ag+HKLSJNZBEGi3bVTbHqzdKPtwpmCnuqLeUYeBpzqG01u3fiFr8vIT4ASfmQAeV6IP9hUUVtNfngsG0tmGzUHPoym/atMG214s/Kk1jj92ixWe9G28xbuBdljGWFwVl46GvzBGIQj86d3s9rf93FZrdMW7s4jJiEZRh5UCeg+3Siu2BrCYrq9MeLcENoYoinrgb3KKCgW0h0jfbJdIyDlodFn4AKIExF94b3TRLf42cnyu1KzuC4N9fChcdgD2tfFzPPEkyscqiQ4785QwbfaZ0DEC6IIWJbx2wJCEQ3/bHgxj1MjlQYRyBJtEz9JPrdXzLPb13fkgJY6vwTV+/+AOWghb8tJ3qcRFzr+7R5qt3kWz79srbSlskORgU1xUGZcusV8UN1PkgAVh84ZnjCY5XAxrp4jbuf24n4A9ebaNUUNdf8Sd4iTu3eUYmI8GaqnrFjfFl+wGchgX0s96ASvuv2jOrpJ8NMwQrZRRnSj/D1/KFSU3BaVpYkYwf7maceBvnVzSV0/xhxSSiUdOGp8/eCkoPSnin49obsmwmqVbTtPM5ISbSm3qjKtFcnOzGvymbHRdoBkW7gJzbHYwhVx6DugVUGwSkw+s1kaDSeXWHFwv4jhUCNS3C6WZv8B4+5yUNLhoX5rTE6HgfsGggV1z2JUadtV9vkXF2OkbdJZYNfTsgkrD2Ada4oysrR/HhiDmJre5Vq4q5IveQfSVNo3phDZcXhI7VtS3EnDJ7In6AjrnnpEiqDwbf6UVWH0fymxuT8M+W39YrxxvsgQaEP2yecld70aJxB3KMIUpBM1UaRcln8nUNpe8A7lZ27Wl7qTpOuvQ7tJtl3Krxmzr3Q9cf+3wX/+94d6yXteJTOP3DDA7+fG5TV84JcC996gkSaCdnUI/IPayl1r00apH4CQaOtJ3wW5EBcw/OIBG6ha5GSVdAW1xGTyi4ixasVbrqNBPVeYN31fg2VyykivIUrDQnvrMMzNwm8UGBnpOuxn9HLzYAWZ8UerZd7I2drV16QjwWRvCZZ4JU2vLt7/sdokyNHWXhbjuR36+dFUDJGqw4Df4oKVwfn9u188ux9pheuG1jwamfbsCgeBcae74o5RYIWtPAdQPDWkyrauucf+4nB3S4YBdgN8W0kgkgOqA+e4hprNeaW1ldOjDahMJyvkjznN1MZLHrR57NZdTx+SpZn/HMT6Io9B56XmA7T4Wr0LaKloyMUOnp/kjmD+fEYZpqqomywHWz2wg7NIlnV2Yvs4SZNFnpW1goQ70b7MBVOcpBqQO33eIth0VtALj3sNmCD2NY139iz3XBvcLM+PnekgjGsEfc4A83U7zCqhHliZo6oICoVvEh7bQWsfH9ANhppXKRulGKH3ltHN12WWQ=="
password = "5 7 10:01 18 90 Dead Sea Bd6 Apple 039"

**Comment by HomelessPhD** [comment]
Try the other puzzles - those that is solved and the solution is known.
Bear in mind that puzzles have a bit different structure and so the
solution constructed is a bit  different from the given options so far
(permutations etc...)

(and what is that message above - how have you got it - thats one of the
first solved puzzles, right?)

**Comment by HomelessPhD** [comment]
I mean - check puzzle 7 or puzzle 5 code - they work with the right answer AND they use similar code (taking into account specific of the puzzle itself)

**Comment by Rivaldiananto** [comment]
> I mean - check puzzle 7 or puzzle 5 code - they work with the right answer AND they use similar code (taking into account specific of the puzzle itself)

yes, i check for puzzle 5 and 7 too, im using your brute go script on python.. thats no make sense, why they didnt stop or pop up the right answer? your code just runing it not to decode cuz when i wrote all down the right answer into puzzle keys .txt theres no giving me any right answers. when i cek into pzl5_bruttedanswers its there, idk whats wrong with it

ps : i mean your code "brute go script" just to make a list, not to decode any msg

**Comment by Rivaldiananto** [comment]
![Screenshot 2024-08-27 051907](https://github.com/user-attachments/assets/38bc921e-81de-45b4-b521-43adbd23b2a4)

sorry but this doesnt any make sense, i dont get it... 



-------------------------------------------------------------------------------------------------------------------------
~/puzzle5$ python3 brute_pzl5_GO.py
unexpected fault address 0xc000400000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0xc000400000 pc=0x487073]

goroutine 1 [running]:
runtime.throw({0x4a2588?, 0xc0002aa280?})
        /usr/lib/go-1.18/src/runtime/panic.go:992 +0x71 fp=0xc000112c30 sp=0xc000112c00 pc=0x430431
runtime.sigpanic()
        /usr/lib/go-1.18/src/runtime/signal_unix.go:825 +0x305 fp=0xc000112c80 sp=0xc000112c30 pc=0x443fa5
crypto/aes.expandKeyAsm(0x0, 0xc0002a8000, 0xc0002aa000, 0xc0002aa280)
        /usr/lib/go-1.18/src/crypto/aes/asm_amd64.s:200 +0x1b3 fp=0xc000112c88 sp=0xc000112c80 pc=0x487073
crypto/aes.newCipher({0xc0002a8000, 0x80, 0xc000142080?})
        /usr/lib/go-1.18/src/crypto/aes/cipher_asm.go:46 +0x16e fp=0xc000112d08 sp=0xc000112c88 pc=0x4869ae
crypto/aes.NewCipher({0xc0002a8000?, 0xc000142080?, 0x0?})
        /usr/lib/go-1.18/src/crypto/aes/cipher.go:40 +0x45 fp=0xc000112d30 sp=0xc000112d08 pc=0x4866a5
main.TiamatDecodeCheck({0x4c2b90, 0xc00010c060}, {0xc000112eb0?, 0x0?})
        /home/hkopjt9/puzzle5/pzl5_GOscript.go:73 +0x366 fp=0xc000112e80 sp=0xc000112d30 pc=0x48a386
main.main()
        /home/hkopjt9/puzzle5/pzl5_GOscript.go:115 +0xe5 fp=0xc000112f80 sp=0xc000112e80 pc=0x48a845
runtime.main()
        /usr/lib/go-1.18/src/runtime/proc.go:250 +0x212 fp=0xc000112fe0 sp=0xc000112f80 pc=0x432b52
runtime.goexit()
        /usr/lib/go-1.18/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000112fe8 sp=0xc000112fe0 pc=0x45b201
FINISH
-------------------------------------------------------------------------------------------------------------------------
