### ISSUE TITLE
Brute Forcer for Puzzle 10 Does Not Work

### ISSUE THREAD

**Issue by adrianhacker-pdx** [HomelessPhD/AR_Puzzles#8]
Tried on both Ubuntu and Windows.  This is as far as the log file gets

15/06/2024 20:59:59: Reading the list of keys.....
15/06/2024 21:00:00: .........keys have been read.
15/06/2024 21:00:00: Reading the brutted answers.....
15/06/2024 21:00:00: .........brutted answers have been read.
15/06/2024 21:00:00: Preparing the list of answers....
15/06/2024 21:00:00: ............ answers list prepared
15/06/2024 21:00:00: 1048577 answers to be brutted, 0 skipped (already been brutted)
15/06/2024 21:00:00: Total size of the answers list is: 1048577
15/06/2024 21:00:00: 0: 0, 131072
15/06/2024 21:00:03: 1: 131073, 262145
15/06/2024 21:00:07: 2: 262146, 393218
15/06/2024 21:00:10: 3: 393219, 524291
15/06/2024 21:00:13: 4: 524292, 655364
15/06/2024 21:00:16: 5: 655365, 786437
15/06/2024 21:00:21: 6: 786438, 917510
15/06/2024 21:00:23: 7: 917511, 1048576
15/06/2024 21:10:42: Reading the list of keys.....
15/06/2024 21:10:43: .........keys have been read.
15/06/2024 21:10:43: Reading the brutted answers.....
15/06/2024 21:10:43: .........brutted answers have been read.
15/06/2024 21:10:43: Preparing the list of answers....
15/06/2024 21:10:43: ............ answers list prepared
15/06/2024 21:10:43: 1048577 answers to be brutted, 0 skipped (already been brutted)
15/06/2024 21:10:43: Total size of the answers list is: 1048577
15/06/2024 21:10:43: 0: 0, 1048576
15/06/2024 21:15:26: Reading the list of keys.....
15/06/2024 21:15:27: .........keys have been read.
15/06/2024 21:15:27: Reading the brutted answers.....
15/06/2024 21:15:27: .........brutted answers have been read.
15/06/2024 21:15:27: Preparing the list of answers....
15/06/2024 21:15:28: ............ answers list prepared
15/06/2024 21:15:28: 1048577 answers to be brutted, 0 skipped (already been brutted)
15/06/2024 21:15:28: Total size of the answers list is: 1048577

**Comment by adrianhacker-pdx** [comment]
C:\Users\ahack\AR_Puzzles\PZL10\Brute\NODEjs [main ≡ +0 ~1 -0 !]> python3 brute_pzl10.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "brute_pzl10.py", line 40, in t_job
    result = os.popen("node pzl10_pageCODE.js "+ " ".join(hashed_answer)).read().strip('\n')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 992, in popen
    bufsize=buffering)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 206] The filename or extension is too long

**Comment by adrianhacker-pdx** [comment]
Since I am using WSL in windows, this should run same as ubuntu

**Comment by HomelessPhD** [comment]
ouufffff...

Well, it can be run on windows (but i written it for linux).... On windows
i guess you'd better reduce the butch size from 500 to something less....
20 or 50.... (and be sure that you have nodjs installed and accessible form
under command line)

and.... JS version is slow.... i guess i shoul add the GO version for the
10 on the github too...
